name: Create tag on PR

on:
  push:
    branches:
      - main
jobs:
  build:
    environment: TEST
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
            
          
      - name: Read Version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt

      - name: Fix version
        id: fixed-version
        run: bash ./get-version-from-pr.sh "${{steps.version.outputs.content}}"
         
      - name: Create Tag
        if: ${{ steps.version.outputs.version }} != ''
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
             ref: "refs/tags/${{ steps.fixed-version.outputs.version }}",
              sha: context.sha
            })
      - uses: actions/checkout@v2
