name: Create Issue
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Issue Title"
        required: true
        default: "New Issue"
      body:
        description: "Issue Body"
        required: true
        default: "New Issue Body"
      file-name:
        description: "File Name"
        required: true
        default: "15/logs-Nov-21-13:50:11.zip"

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: dacbd/create-issue-action@v1
        id: new-issue
        with:
          title: ${{ github.event.inputs.title }}
          body: |
            ${{ github.event.inputs.body }}
            Please download the file from the link below:
          labels: ${{ github.event.inputs.labels }}
          assignees: "IsmailAlamKhan"
          token: ${{ secrets.PAT }}
      - name: Issue json
        run: |

          echo "${{ steps.new-issue.outputs.json }}" | json url
