name: Create tag on PR

on:
  push:
    branches:
      - main
jobs:
  build:
    if: contains( github.event.head_commit.message, 'Updating to' )
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
            
          
      - name : Get version from pr
        run: bash ./get-version-from-pr.sh "${{ github.event.pull_request.title }}"
        id: version
      

      - name: Create tag from version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.version }}
          message: "New version ${{ steps.version.outputs.version }}"
