name: Create tag on PR

on:
  push:
    branches:
      - main
jobs:
  build:
    if: contains( github.event.head_commit.message, 'Updating to' )
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
            
          
      - name : Get version from msg
        run: bash ./get-version-from-pr.sh "${{ github.event.head_commit.message }}"
        id: version
      

#       - name: Create tag from version
#         uses: rickstaa/action-create-tag@v1
#         with:
#           tag: ${{ steps.version.outputs.version }}
#           message: "New version ${{ steps.version.outputs.version }}"
      - name: Create Tag
        uses: actions/github-script@v3
        env:
          TAG: ${{ steps.version.outputs.version }}
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
             ref: "refs/tags/${{ steps.version.outputs.version }}",
              sha: context.sha
            })
      - uses: actions/checkout@v2
