name: Create tag on PR

on:
  push:
    branches: [main]
  pull_request:
    types:
          - closed

    
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
#       - name: Read Version
#         id: version
#         uses: juliangruber/read-file-action@v1
#         with:
#           path: ./version.txt
          
          
      - name : Get version from pr
        run: bash ./get-version-from-pr.sh "${{ github.event.pull_request.title }}"
        id: version
      

      - name: Create tag from version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.version }}
          message: "New version ${{ steps.version.outputs.version }}"
