name: Create tag on PR

on:
  push:
    branches:
      - main
jobs:
  build:
    environment: TEST
    if: contains( github.event.head_commit.message, 'Updating to' )
#     if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
            
          
      - name : Get version from msg
        run: bash ./get-version-from-pr.sh "${{ github.event.head_commit.message }}"
        id: version
    
      - name: Create Tag
        if: ${{ steps.version.outputs.version }} != ''
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
             ref: "refs/tags/${{ steps.version.outputs.version }}",
              sha: context.sha
            })
      - uses: actions/checkout@v2
