name: HTTP test workflow

on:
  workflow_dispatch:

jobs:
  http_test:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        id: myRequest
        run: |
          response=$(curl https://deto-events.com/v1/version)
          # echo "::set-output name=response::$(echo response from curl= $response)"
          echo "response=$response" >> $GITHUB_OUTPUT

      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }} > response.json

      - name: Upload Response
        uses: actions/upload-artifact@v3
        with:
          name: response.json
          path: response.json
# echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
