name: HTTP test workflow

on:
  workflow_dispatch:

jobs:
  http_test:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        id: myRequest
        run: |
          response=$(curl https://deto-events.com/v1/version)
          response=$(curl https://deto-events.com/v1/version)
          echo "::set-output name=response::$(echo response from curl= $response)"

      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}

# echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
