name: Release with tag

on:
  push:
    tags:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: "Release ${{ github.ref }}"
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
